---
do_token: ansible_env.DO_TOKEN

droplets:
  kubernetes-master-1:
    image_id: ubuntu-16-04-x64
    size_id: 4gb
    region_id: ams2
  kubernetes-etcd-1:
    image_id: ubuntu-16-04-x64
    size_id: 2gb
    region_id: ams2
  kubernetes-worker-1:
    image_id: ubuntu-16-04-x64
    size_id: 2gb
    region_id: ams2
  kubernetes-worker-2:
    image_id: ubuntu-16-04-x64
    size_id: 2gb
    region_id: ams2
