---
- hosts: masters etcd nodes
  become_user: root
  become: true

  tasks:

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - python
