Vagrant.require_version ">= 1.9.1"

Vagrant.configure("2") do |config|

  config.vm.define "sample-provisioning" do |config|
    config.vm.provider :digital_ocean do |provider, override|
      override.vm.box = "digital_ocean"
      override.vm.box_url = "https://github.com/devops-group-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
      override.ssh.private_key_path = ENV["DO_PRIVATE_KEYPATH"]
      provider.token = ENV["DO_TOKEN"]
      provider.image = "debian-8-x64"
      provider.region = "ams2"
      provider.size = "512mb"
    end
  end

  config.vm.synced_folder ".", "/vagrant",
    id: "default",
    disabled: true,
    type: "rsync",
    create: true

  config.vm.synced_folder "data/", "/vagrant/data",
    id: "data",
    disabled: false,
    type: "rsync",
    create: true

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
  end

end
