---
# file: common/tasks/main.yml
- name: Configure hosts
  template:
    src: hosts.txt
    dest: /etc/hosts

- name: System update
  apt:
    upgrade: dist
    force: yes
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - build-essential
    - htop
    - curl
