---
- name: "Pre-upgrade | copy /var/lib/cni from kubelet"
  command: docker cp kubelet:/var/lib/cni /var/lib/cni
  args:
    creates: "/var/lib/cni"
  failed_when: false

- name: "Pre-upgrade | ensure kubelet container is stopped if using host deployment"
  command: docker stop kubelet
  failed_when: false
  changed_when: false
  when: kubelet_deployment_type == 'host'
