---
# file: playbook.yml
- name: common configuration
  hosts: all
  remote_user: admin
  become: true
  roles:
    - common
    - ec2
    - java

- name: provision java app
  hosts: java
  remote_user: admin
  become: true
  roles:
    - java-app
