---
- name: provision kafka nodes
  hosts: kafka
  remote_user: admin
  become: true
  roles:
    - common
    - java
    - kafka

- name: provision flink nodes
  hosts: flink
  remote_user: admin
  become: true
  roles:
    - common
    - java
    - flink

- name: provision neo4j nodes
  hosts: neo4j
  remote_user: admin
  become: true
  roles:
    - common
    - java
    - neo4j
