---
- name: Ensure ssh key exists
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa

- name: Ensure SSH key exists at DigitalOcean
  digital_ocean:
    command: ssh
    state: present
    name: gmarciani@do_kubernetes
    ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    api_token: "{{ lookup('env','DO_TOKEN') }}"
  register: my_ssh_key

- name: Ensure droplets destroyed
  digital_ocean:
    command: droplet
    state: absent
    name: "{{ item.name }}"
    image_id: "{{ item.image_id }}"
    size_id: "{{ item.size_id }}"
    region_id: "{{ item.region_id }}"
    ssh_key_ids: "{{ my_ssh_key.ssh_key.id }}"
    unique_name: yes
    api_token: "{{ lookup('env','DO_TOKEN') }}"
  with_items: "{{ droplets }}"
  register: droplet_info

- name: Ensure tags destroyed
  digital_ocean_tag:
    name: "{{ item }}"
    state: absent
    api_token: "{{ lookup('env','DO_TOKEN') }}"
  with_items: "{{ tags }}"
  when: "proxy.http == ''"
