---
# file: neo4j_master/vars/mail.yml
## Neo4J CE
#neo4j_download: https://neo4j.com/artifact.php?name=neo4j-community-3.1.1-unix.tar.gz
#neo4j_archive_path: /tmp/neo4j-community-3.1.1-unix.tar.gz
#neo4j_home: /opt/neo4j-community-3.1.1
##

## Neo4J EE
neo4j_download: https://www.dropbox.com/s/d1hahugy19mcmew/neo4j-enterprise-3.1.3-unix.tar.gz?dl=1
neo4j_archive_path: /tmp/neo4j-enterprise-3.1.3-unix.tar.gz
neo4j_home: /opt/neo4j-enterprise-3.1.3
##
neo4j_manager_path: /opt/systemd/neo4j-manager.sh
neo4j_hostname: localhost
neo4j_http_port: 7474
neo4j_https_port: 7473
neo4j_bolt_port: 7687
neo4j_dbname: graph.db
neo4j_username: neo4j
neo4j_password: password
neo4j_start_wait: 60 # seconds
neo4j_start_pool: 3 # seconds
neo4j_jvm_heap_min: 512m
neo4j_jvm_heap_max: 512m
neo4j_dbms_mode: HA
neo4j_ha_server_id: "{{ play_hosts.index(inventory_hostname) + 1 }}"
neo4j_ha_initial_hosts: "{{ hostvars['do-neo4j-master']['ansible_ssh_host'] }}:5001,{{ hostvars['do-neo4j-slave-1']['ansible_ssh_host'] }}:5001,{{ hostvars['do-neo4j-slave-2']['ansible_ssh_host'] }}:5001"
