---
- include: ../shared/check_vault.yml
  when: inventory_hostname in groups.vault

- include: ../shared/check_etcd.yml
  when: inventory_hostname in groups.vault

- include: configure.yml
  when: inventory_hostname in groups.vault

- include: binary.yml
  when: inventory_hostname in groups.vault and vault_deployment_type == "host"

- include: systemd.yml
  when: inventory_hostname in groups.vault

- include: init.yml
  when: inventory_hostname in groups.vault

- include: unseal.yml
  when: inventory_hostname in groups.vault

- include: ../shared/find_leader.yml
  when: inventory_hostname in groups.vault

- include: create_mounts.yml
  when: inventory_hostname == groups.vault|first

- include: ../shared/gen_ca.yml
  vars:
    gen_ca_cert_dir: "{{ vault_pki_mounts.kube.cert_dir }}"
    gen_ca_mount_path: "{{ vault_pki_mounts.kube.name }}"
    gen_ca_vault_headers: "{{ vault_headers }}"
    gen_ca_vault_options: "{{ vault_ca_options.kube }}"
  when: inventory_hostname in groups.vault

- include: ../shared/auth_backend.yml
  vars:
    auth_backend_description: A Username/Password Auth Backend primarily used for services needing to issue certificates
    auth_backend_path: userpass
    auth_backend_type: userpass
  when: inventory_hostname == groups.vault|first

- include: create_roles.yml
  with_items:
    - "{{ vault_pki_mounts.vault }}"
    - "{{ vault_pki_mounts.etcd }}"
    - "{{ vault_pki_mounts.kube }}"
  loop_control:
    loop_var: mount
  when: inventory_hostname in groups.vault
