Vagrant.require_version ">= 1.9.1"

Vagrant.configure("2") do |config|

  config.vm.define "sample-provisioning" do |config|
    config.vm.box = "dummy"

    config.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV["AWS_ACCESS_KEY_ID"]
      aws.secret_access_key = ENV["AWS_ACCESS_KEY_SECRET"]
      aws.keypair_name = ENV["AWS_KEYPAIR_NAME"]

      aws.region = "eu-west-1"
      aws.instance_type = "t2.micro"
      aws.ami = "ami-7d9ea61b"

      #Install python2.7 for ansible
      #aws.user_data = "#!/bin/bash\napt-get install --yes python2.7\nln -s /usr/bin/python2.7 /usr/bin/python"

      override.ssh.username = "gmarciani"
      override.ssh.private_key_path = ENV["AWS_KEYPAIR_PATH"]
    end
  end

  config.vm.synced_folder ".", "/vagrant",
    id: "default",
    disabled: true,
    type: "rsync",
    create: true

  config.vm.synced_folder "data/", "/vagrant/data",
    id: "data",
    disabled: false,
    type: "rsync",
    create: true

  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "ansible/playbook.yml"
  #end

end
