Vagrant.require_version ">= 1.9.1"

Vagrant.configure("2") do |config|

#*******************************************************************************
# INSTANCE_FRONT
#*******************************************************************************
  config.vm.define "instance_front" do |config|
    config.vm.box = "dummy"

    config.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV["AWS_ACCESS_KEY_ID"]
      aws.secret_access_key = ENV["AWS_ACCESS_KEY_SECRET"]
      aws.keypair_name = ENV["AWS_KEYPAIR_NAME"]

      aws.region = "eu-west-1"
      aws.instance_type = "t2.micro"
      aws.ami = "ami-3291be54" # debian jessie x64

      aws.tags = {
        "Name" => "vagrant_instance_front"
      }

      override.ssh.username = "admin"
      override.ssh.private_key_path = ENV["AWS_KEYPAIR_PATH"]
    end

    config.vm.synced_folder "data/instance_front/", "/vagrant/data",
      id: "data",
      disabled: false,
      type: "rsync",
      create: true
  end

#*******************************************************************************
# INSTANCE_CORE
#*******************************************************************************
  config.vm.define "instance_core" do |config|
    config.vm.box = "dummy"

    config.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV["AWS_ACCESS_KEY_ID"]
      aws.secret_access_key = ENV["AWS_ACCESS_KEY_SECRET"]
      aws.keypair_name = ENV["AWS_KEYPAIR_NAME"]

      aws.region = "eu-west-1"
      aws.instance_type = "t2.micro"
      aws.ami = "ami-3291be54" # debian jessie x64

      aws.tags = {
        "Name" => "vagrant_instance_core"
      }

      override.ssh.username = "admin"
      override.ssh.private_key_path = ENV["AWS_KEYPAIR_PATH"]
    end

    config.vm.synced_folder "data/instance_core", "/vagrant/data",
      id: "data",
      disabled: false,
      type: "rsync",
      create: true
  end

#*******************************************************************************
# INSTANCE_BACK
#*******************************************************************************
  config.vm.define "instance_back" do |config|
    config.vm.box = "dummy"

    config.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV["AWS_ACCESS_KEY_ID"]
      aws.secret_access_key = ENV["AWS_ACCESS_KEY_SECRET"]
      aws.keypair_name = ENV["AWS_KEYPAIR_NAME"]

      aws.region = "eu-west-1"
      aws.instance_type = "t2.micro"
      aws.ami = "ami-3291be54" # debian jessie x64

      aws.tags = {
        "Name" => "vagrant_instance_back"
      }

      override.ssh.username = "admin"
      override.ssh.private_key_path = ENV["AWS_KEYPAIR_PATH"]
    end

    config.vm.synced_folder "data/instance_back", "/vagrant/data",
      id: "data",
      disabled: false,
      type: "rsync",
      create: true
  end

#*******************************************************************************
# COMMON
#*******************************************************************************
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/playbook.yml"
  end

end
